### PR TITLE
Switch to rollup-plugin-ts plugin to bundle types declarations.

### PR DESCRIPTION
**Pull request by jerome-benoit**
Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] If your changes contain any new feature please be sure to document it.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Comment by Shinigami92** [comment]
Could you explain the benefit of `rollup-plugin-ts` over `rollup-plugin-typescript2`?  
As far as I can tell `rollup-plugin-typescript2` has MUCH more downloads :thinking: and is really well known

**Comment by jerome-benoit** [comment]
> Could you explain the benefit of `rollup-plugin-ts` over `rollup-plugin-typescript2`?
> As far as I can tell `rollup-plugin-typescript2` has MUCH more downloads 🤔 and is really well known

The types declarations are also bundled properly. And I would not say that the current TS plugin is maintained.

**Review by Shinigami92 — APPROVED** [review]
You got me with `not maintained anymore` :+1:

**Comment by jerome-benoit** [comment]
> You got me with `not maintained anymore` 👍

There's another TS plugin for rollup that seems maintained but it requires dependencies like babel or tslib, too heavy dependencies. That one can work standalone.

**Review by pioardi — APPROVED** [review]

**Pull request merged**
